# Generated by Django 5.0.3 on 2024-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerIncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entryType', models.CharField(choices=[('income', 'INCOME'), ('expense', 'EXPENSE')], default='income', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TrackerIncome',
        ),
    ]
